### ISSUE TITLE
Broker?

### ISSUE THREAD

**Issue by santiagonn** [frxncisjoseph/belfort#2]
This is going to work with iq option? or will be for binary.com ?
Do you have a release date?

**Comment by frxncisjoseph** [comment]
This robot will specifically be designed for https://www.binary.com upon release due to the language it is written in. 

Binary.com offers a full-scale public API which supports various options that are necessary for this robot to operate. Such as, ticks, purchasing, selling, multiple accounts and so forth. 

There are no plans to support IQ Option in the future although the aspect of polymorphism is interesting.
